"""AI/LLM Assistant service (AI-01 ~ AI-07).

Covers:
- Strategy drafting and code generation
- Research explanation and analysis
- Trading recommendations
- Risk advisory
- Knowledge augmentation with market data
"""

from __future__ import annotations

import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ─────────────────────────────────────────────────────────────────────────────
# Enums
# ─────────────────────────────────────────────────────────────────────────────

class AIIntent(str, Enum):
    STRATEGY_DRAFT = "strategy_draft"
    STRATEGY_EXPLAIN = "strategy_explain"
    RESEARCH_ANALYSIS = "research_analysis"
    RECOMMENDATION = "recommendation"
    RISK_ADVISORY = "risk_advisory"
    SCREENER_QUERY = "screener_query"
    CHART_EXPLANATION = "chart_explanation"
    PORTFOLIO_REVIEW = "portfolio_review"
    GENERAL = "general"


class RecommendationAction(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    REDUCE = "reduce"
    INCREASE = "increase"
    CLOSE = "close"
    MONITOR = "monitor"


class RiskLevel(str, Enum):
    VERY_LOW = "very_low"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    VERY_HIGH = "very_high"
    EXTREME = "extreme"


@dataclass(slots=True)
class ConfidenceScore:
    """Confidence score for AI output."""

    overall: float  # 0.0 - 1.0
    factors: dict[str, float] = field(default_factory=dict)
    sample_size: int = 0
    backtest_years: float = 0.0


# ─────────────────────────────────────────────────────────────────────────────
# Data Models
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(slots=True)
class ConversationTurn:
    """A single turn in a conversation with the AI assistant."""

    turn_id: str
    user_id: str
    intent: AIIntent
    query: str
    context: dict[str, Any] = field(default_factory=dict)
    response: str = ""
    model_used: str = "quant-gpt-4"
    tokens_used: int = 0
    created_at: str = field(default_factory=_now)


@dataclass(slots=True)
class StrategyDraft:
    """A generated strategy draft."""

    draft_id: str
    user_id: str
    name: str
    description: str
    strategy_code: str  # Python/QuantScript code
    language: str = "python"  # python, quant_script
    indicators: tuple[str, ...] = field(default_factory=tuple)
    timeframes: tuple[str, ...] = field(default_factory=lambda: ("1d",))
    instruments: tuple[str, ...] = field(default_factory=tuple)
    parameters: dict[str, float] = field(default_factory=dict)
    risk_level: RiskLevel = RiskLevel.MEDIUM
    expected_return_pct: float | None = None
    sharpe_ratio: float | None = None
    max_drawdown_pct: float | None = None
    confidence: ConfidenceScore | None = None
    approved: bool = False
    created_at: str = field(default_factory=_now)
    reviewed_at: str | None = None


@dataclass(slots=True)
class ResearchExplanation:
    """Explanation of a strategy, indicator, or market concept."""

    explanation_id: str
    user_id: str
    topic: str  # strategy name, indicator name, concept
    content: str
    format: str = "text"  # text, markdown, html
    examples: tuple[str, ...] = field(default_factory=tuple)
    related_topics: tuple[str, ...] = field(default_factory=tuple)
    citations: tuple[str, ...] = field(default_factory=tuple)
    created_at: str = field(default_factory=_now)


@dataclass(slots=True)
class TradingRecommendation:
    """A trading recommendation generated by the AI."""

    recommendation_id: str
    user_id: str
    instrument_id: str
    action: RecommendationAction
    entry_price: float | None = None
    target_price: float | None = None
    stop_loss: float | None = None
    time_horizon: str = ""  # intraday, short_term, medium_term, long_term
    confidence: ConfidenceScore | None = None
    reasoning: str = ""
    risk_factors: tuple[str, ...] = field(default_factory=tuple)
    conditions: tuple[str, ...] = field(default_factory=tuple)
    status: str = "pending"  # pending, triggered, expired, fulfilled
    created_at: str = field(default_factory=_now)
    expires_at: str | None = None


@dataclass(slots=True)
class RiskAdvisory:
    """AI-generated risk advisory."""

    advisory_id: str
    user_id: str
    risk_level: RiskLevel
    portfolio_id: str | None = None
    var_pct: float | None = None  # Value at Risk percentage
    max_drawdown_pct: float | None = None
    concentration_risk: dict[str, float] = field(default_factory=dict)  # instrument -> weight
    leverage_used: float = 1.0
    margin_utilization_pct: float = 0.0
    recommendations: tuple[str, ...] = field(default_factory=tuple)
    alerts: tuple[str, ...] = field(default_factory=tuple)
    analysis: str = ""
    created_at: str = field(default_factory=_now)


@dataclass(slots=True)
class KnowledgeGraphEntry:
    """Entry in the AI knowledge graph."""

    entity_id: str
    entity_type: str  # instrument, indicator, strategy, concept, event
    name: str
    description: str
    properties: dict[str, Any] = field(default_factory=dict)
    relationships: dict[str, list[str]] = field(default_factory=dict)  # relation_type -> [entity_ids]
    embedding: list[float] | None = None  # vector embedding
    updated_at: str = field(default_factory=_now)


@dataclass(slots=True)
class AIGlobalConfig:
    """Global AI service configuration."""

    config_id: str
    default_model: str = "quant-gpt-4"
    max_tokens_per_request: int = 8192
    temperature: float = 0.7
    enable_reasoning: bool = True
    enable_citations: bool = True
    enable_knowledge_graph: bool = True
    custom_instructions: str = ""
    enabled_intents: tuple[AIIntent, ...] = field(
        default_factory=lambda: (
            AIIntent.STRATEGY_DRAFT, AIIntent.STRATEGY_EXPLAIN,
            AIIntent.RESEARCH_ANALYSIS, AIIntent.RECOMMENDATION,
            AIIntent.RISK_ADVISORY,
        )
    )


# ─────────────────────────────────────────────────────────────────────────────
# AI Assistant Service
# ─────────────────────────────────────────────────────────────────────────────

class AIAssistantService:
    """AI/LLM Assistant service (AI-01 ~ AI-07).

    Provides:
    - Strategy drafting and code generation
    - Research explanation and analysis
    - Trading recommendations
    - Risk advisory
    - Knowledge augmentation
    """

    def __init__(self, persistence=None, llm_client=None) -> None:
        self.persistence = persistence
        self._conversations: dict[str, list[ConversationTurn]] = {}
        self._drafts: dict[str, StrategyDraft] = {}
        self._explanations: dict[str, ResearchExplanation] = {}
        self._recommendations: dict[str, TradingRecommendation] = {}
        self._advisories: dict[str, RiskAdvisory] = {}
        self._knowledge_graph: dict[str, KnowledgeGraphEntry] = {}
        self._user_configs: dict[str, AIGlobalConfig] = {}
        self._id_counter = 0
        self._llm_client = llm_client  # Optional LLM client for AI-01~AI-07

    # ── Intent Detection ─────────────────────────────────────────────────

    def detect_intent(self, query: str) -> AIIntent:
        """Detect user intent from natural language query."""
        query_lower = query.lower()

        if any(kw in query_lower for kw in ["strategy", "write code", "build", "create strategy", "trading system"]):
            return AIIntent.STRATEGY_DRAFT
        if any(kw in query_lower for kw in ["explain", "what is", "how does", "what does", "understand"]):
            return AIIntent.STRATEGY_EXPLAIN
        if any(kw in query_lower for kw in ["analyze", "research", "outlook", "forecast"]):
            return AIIntent.RESEARCH_ANALYSIS
        if any(kw in query_lower for kw in ["recommend", "should i", "buy", "sell", "signal"]):
            return AIIntent.RECOMMENDATION
        if any(kw in query_lower for kw in ["risk", "drawdown", "exposure", "volatility", "var"]):
            return AIIntent.RISK_ADVISORY
        if any(kw in query_lower for kw in ["screen", "find stocks", "filter", "scanner"]):
            return AIIntent.SCREENER_QUERY
        if any(kw in query_lower for kw in ["chart", "price", "candle", "pattern"]):
            return AIIntent.CHART_EXPLANATION
        if any(kw in query_lower for kw in ["portfolio", "review", "allocation", "positions"]):
            return AIIntent.PORTFOLIO_REVIEW
        return AIIntent.GENERAL

    # ── Conversation Management ────────────────────────────────────────────

    def create_conversation(self, user_id: str) -> str:
        """Start a new conversation thread."""
        conv_id = f"conv:{uuid.uuid4().hex[:12]}"
        self._conversations[conv_id] = []
        return conv_id

    def add_turn(
        self,
        conv_id: str,
        user_id: str,
        query: str,
        context: dict[str, Any] | None = None,
        model_used: str = "quant-gpt-4",
    ) -> ConversationTurn | None:
        """Add a turn to a conversation."""
        if conv_id not in self._conversations:
            return None
        intent = self.detect_intent(query)
        turn = ConversationTurn(
            turn_id=f"turn:{uuid.uuid4().hex[:12]}",
            user_id=user_id,
            intent=intent,
            query=query,
            context=context or {},
            model_used=model_used,
        )
        self._conversations[conv_id].append(turn)
        return turn

    def get_conversation(self, conv_id: str) -> list[ConversationTurn] | None:
        """Get all turns in a conversation."""
        return self._conversations.get(conv_id)

    def get_user_conversations(self, user_id: str) -> list[dict[str, Any]]:
        """Get all conversation summaries for a user."""
        result = []
        for conv_id, turns in self._conversations.items():
            if turns and turns[0].user_id == user_id:
                result.append({
                    "conv_id": conv_id,
                    "turn_count": len(turns),
                    "last_query": turns[-1].query[:100],
                    "last_intent": turns[-1].intent.value,
                    "created_at": turns[0].created_at,
                    "updated_at": turns[-1].created_at,
                })
        return result

    # ── Strategy Drafting ─────────────────────────────────────────────────

    def draft_strategy(
        self,
        user_id: str,
        description: str,
        name: str = "",
        language: str = "python",
    ) -> StrategyDraft:
        """Generate a strategy draft from natural language description."""
        draft_id = f"draft:{uuid.uuid4().hex[:12]}"

        # Parse description to extract indicators, timeframes, instruments
        indicators = self._extract_indicators(description)
        timeframes = self._extract_timeframes(description)
        instruments = self._extract_instruments(description)
        risk_level = self._assess_risk_level(description)

        # Generate strategy code (simplified template)
        strategy_code = self._generate_strategy_code(
            description, language, indicators, timeframes
        )

        draft = StrategyDraft(
            draft_id=draft_id,
            user_id=user_id,
            name=name or f"Strategy {draft_id[-12:]}",
            description=description,
            strategy_code=strategy_code,
            language=language,
            indicators=tuple(indicators),
            timeframes=tuple(timeframes),
            instruments=tuple(instruments),
            risk_level=risk_level,
            created_at=_now(),
        )
        self._drafts[draft_id] = draft
        return draft

    def _extract_indicators(self, description: str) -> list[str]:
        """Extract indicator names from description."""
        indicator_keywords = {
            "ma": "MA", "moving average": "MA", "sma": "MA",
            "ema": "EMA", "exponential moving average": "EMA",
            "rsi": "RSI", "relative strength": "RSI",
            "macd": "MACD",
            "bollinger": "BOLLINGER", "bollinger bands": "BOLLINGER",
            "atr": "ATR", "average true range": "ATR",
            "volume": "VOLUME",
            "stoch": "STOCH", "stochastic": "STOCH",
            "vwap": "VWAP",
            "obv": "OBV",
        }
        found = []
        desc_lower = description.lower()
        for kw, indicator in indicator_keywords.items():
            if kw in desc_lower and indicator not in found:
                found.append(indicator)
        return found

    def _extract_timeframes(self, description: str) -> list[str]:
        """Extract timeframes from description."""
        timeframes = []
        desc_lower = description.lower()
        tf_map = {
            "1 minute": "1m", "1min": "1m", "minute": "1m",
            "5 minute": "5m", "5min": "5m",
            "15 minute": "15m", "15min": "15m",
            "1 hour": "1h", "1hour": "1h", "hourly": "1h",
            "4 hour": "4h", "4hour": "4h",
            "daily": "1d", "day": "1d", "1 day": "1d",
            "weekly": "1w", "week": "1w",
        }
        for kw, tf in tf_map.items():
            if kw in desc_lower:
                if tf not in timeframes:
                    timeframes.append(tf)
        if not timeframes:
            timeframes = ["1d"]
        return timeframes

    def _extract_instruments(self, description: str) -> list[str]:
        """Extract instrument patterns from description."""
        instruments = []
        desc_lower = description.lower()
        if any(sym in desc_lower for sym in ["aapl", "apple"]):
            instruments.append("AAPL")
        if any(sym in desc_lower for sym in ["btc", "bitcoin"]):
            instruments.append("BTC")
        if any(sym in desc_lower for sym in ["eth", "ethereum"]):
            instruments.append("ETH")
        if any(sym in desc_lower for sym in ["spy", "s&p", "sp500"]):
            instruments.append("SPY")
        if any(sym in desc_lower for sym in ["qqq", "nasdaq"]):
            instruments.append("QQQ")
        return instruments

    def _assess_risk_level(self, description: str) -> RiskLevel:
        """Assess risk level from description."""
        desc_lower = description.lower()
        high_risk = ["high risk", "aggressive", "leverage", "futures", "options"]
        low_risk = ["low risk", "conservative", "stable", "bonds", "treasury"]

        if any(kw in desc_lower for kw in high_risk):
            return RiskLevel.HIGH
        if any(kw in desc_lower for kw in low_risk):
            return RiskLevel.LOW
        return RiskLevel.MEDIUM

    def _generate_strategy_code(
        self, description: str, language: str, indicators: list[str], timeframes: list[str]
    ) -> str:
        """Generate strategy code from description."""
        if language == "python":
            code = f'''"""
Generated strategy: {description[:80]}
"""
from quant_exchange import Strategy, DataSource

class GeneratedStrategy(Strategy):
    def __init__(self):
        self.name = "Generated Strategy"
        self.timeframes = {timeframes}
        self.indicators = {indicators}

    def on_tick(self, tick):
        # Strategy logic for: {description[:100]}
        pass

    def on_bar(self, bar):
        # Bar-based strategy logic
        pass
'''
        else:
            code = f'''// QuantScript strategy
// Description: {description[:80]}
INDICATORS: {", ".join(indicators) if indicators else "NONE"}
TIMEFRAMES: {", ".join(timeframes)}
'''
        return code

    def get_draft(self, draft_id: str) -> StrategyDraft | None:
        """Get a strategy draft by ID."""
        return self._drafts.get(draft_id)

    def get_user_drafts(self, user_id: str) -> list[StrategyDraft]:
        """Get all drafts for a user."""
        return [d for d in self._drafts.values() if d.user_id == user_id]

    def approve_draft(self, draft_id: str, approved: bool = True) -> StrategyDraft | None:
        """Approve or reject a strategy draft."""
        draft = self._drafts.get(draft_id)
        if not draft:
            return None
        draft.approved = approved
        draft.reviewed_at = _now()
        return draft

    # ── Research Explanations ─────────────────────────────────────────────

    def explain_topic(
        self,
        user_id: str,
        topic: str,
        format: str = "text",
    ) -> ResearchExplanation:
        """Generate an explanation for a strategy, indicator, or concept."""
        explanation_id = f"expl:{uuid.uuid4().hex[:12]}"
        content = self._generate_explanation(topic)
        related = self._find_related_topics(topic)

        explanation = ResearchExplanation(
            explanation_id=explanation_id,
            user_id=user_id,
            topic=topic,
            content=content,
            format=format,
            related_topics=tuple(related),
            created_at=_now(),
        )
        self._explanations[explanation_id] = explanation
        return explanation

    def _generate_explanation(self, topic: str) -> str:
        """Generate explanation content for a topic."""
        topic_lower = topic.lower()
        if "rsi" in topic_lower:
            return (
                "The Relative Strength Index (RSI) is a momentum oscillator that measures "
                "the speed and change of price movements. Developed by J. Welles Wilder, RSI "
                "oscillates between 0 and 100. Traditionally, RSI above 70 suggests "
                "overbought conditions, while below 30 suggests oversold conditions. "
                "It can be used to identify potential reversal points and confirm trend strength."
            )
        if "macd" in topic_lower:
            return (
                "MACD (Moving Average Convergence Divergence) is a trend-following momentum "
                "indicator that shows the relationship between two moving averages of a "
                "security's price. The MACD is calculated by subtracting the 26-period EMA "
                "from the 12-period EMA. A 9-period EMA of the MACD (signal line) is then "
                "plotted on top of the MACD, which can act as a trigger for buy and sell signals."
            )
        if "bollinger" in topic_lower:
            return (
                "Bollinger Bands are a volatility indicator invented by John Bollinger. "
                "They consist of a middle band (typically 20-period SMA) and two outer bands "
                "at standard deviations (typically 2) above and below the middle band. "
                "When bands widen, volatility increases; when they contract, volatility decreases. "
                "Price touching the upper band may indicate overbought, and touching the lower "
                "band may indicate oversold conditions."
            )
        if "ma" in topic_lower or "moving average" in topic_lower:
            return (
                "A Moving Average (MA) is a technical indicator that smooths price data by "
                "creating a constantly updated average price. The Simple Moving Average (SMA) "
                "calculates the arithmetic mean of a set of values over a specified period. "
                "The Exponential Moving Average (EMA) gives more weight to recent prices. "
                "MAs are used to identify trend direction, support/resistance levels, and "
                "generate trading signals."
            )
        return f"Explanation for '{topic}' is not yet available in the knowledge base."

    def _find_related_topics(self, topic: str) -> list[str]:
        """Find related topics for a given topic."""
        relations = {
            "rsi": ["MACD", "Stochastic", "Momentum", "Overbought/Oversold"],
            "macd": ["RSI", "Moving Average", "Signal Line", "Momentum"],
            "bollinger": ["Moving Average", "Volatility", "Support/Resistance"],
            "ma": ["EMA", "Trend", "Moving Average Crossover"],
            "ema": ["MA", "Exponential Smoothing", "Trend"],
            "atr": ["Volatility", "Stop Loss", "True Range"],
        }
        topic_lower = topic.lower()
        for key, values in relations.items():
            if key in topic_lower:
                return values
        return []

    def get_explanation(self, explanation_id: str) -> ResearchExplanation | None:
        """Get an explanation by ID."""
        return self._explanations.get(explanation_id)

    # ── Trading Recommendations ────────────────────────────────────────────

    def generate_recommendation(
        self,
        user_id: str,
        instrument_id: str,
        action: RecommendationAction,
        reasoning: str = "",
        entry_price: float | None = None,
        target_price: float | None = None,
        stop_loss: float | None = None,
        time_horizon: str = "medium_term",
        confidence: ConfidenceScore | None = None,
        risk_factors: list[str] | None = None,
        conditions: list[str] | None = None,
        expires_at: str | None = None,
    ) -> TradingRecommendation:
        """Generate a trading recommendation."""
        recommendation_id = f"rec:{uuid.uuid4().hex[:12]}"
        recommendation = TradingRecommendation(
            recommendation_id=recommendation_id,
            user_id=user_id,
            instrument_id=instrument_id,
            action=action,
            entry_price=entry_price,
            target_price=target_price,
            stop_loss=stop_loss,
            time_horizon=time_horizon,
            confidence=confidence,
            reasoning=reasoning,
            risk_factors=tuple(risk_factors) if risk_factors else (),
            conditions=tuple(conditions) if conditions else (),
            expires_at=expires_at,
            created_at=_now(),
        )
        self._recommendations[recommendation_id] = recommendation
        return recommendation

    def get_recommendation(self, recommendation_id: str) -> TradingRecommendation | None:
        """Get a recommendation by ID."""
        return self._recommendations.get(recommendation_id)

    def get_active_recommendations(
        self, user_id: str, instrument_id: str | None = None
    ) -> list[TradingRecommendation]:
        """Get all active (pending) recommendations for a user."""
        recs = [
            r for r in self._recommendations.values()
            if r.user_id == user_id and r.status == "pending"
        ]
        if instrument_id:
            recs = [r for r in recs if r.instrument_id == instrument_id]
        return recs

    def update_recommendation_status(
        self, recommendation_id: str, status: str
    ) -> TradingRecommendation | None:
        """Update the status of a recommendation."""
        rec = self._recommendations.get(recommendation_id)
        if rec:
            rec.status = status
        return rec

    # ── Risk Advisory ─────────────────────────────────────────────────────

    def generate_risk_advisory(
        self,
        user_id: str,
        portfolio_id: str | None,
        risk_level: RiskLevel,
        analysis: str = "",
        var_pct: float | None = None,
        max_drawdown_pct: float | None = None,
        concentration_risk: dict[str, float] | None = None,
        leverage_used: float = 1.0,
        margin_utilization_pct: float = 0.0,
        recommendations: list[str] | None = None,
        alerts: list[str] | None = None,
    ) -> RiskAdvisory:
        """Generate a risk advisory report."""
        advisory_id = f"adv:{uuid.uuid4().hex[:12]}"
        advisory = RiskAdvisory(
            advisory_id=advisory_id,
            user_id=user_id,
            portfolio_id=portfolio_id,
            risk_level=risk_level,
            var_pct=var_pct,
            max_drawdown_pct=max_drawdown_pct,
            concentration_risk=concentration_risk or {},
            leverage_used=leverage_used,
            margin_utilization_pct=margin_utilization_pct,
            recommendations=tuple(recommendations) if recommendations else (),
            alerts=tuple(alerts) if alerts else (),
            analysis=analysis,
            created_at=_now(),
        )
        self._advisories[advisory_id] = advisory
        return advisory

    def get_advisory(self, advisory_id: str) -> RiskAdvisory | None:
        """Get a risk advisory by ID."""
        return self._advisories.get(advisory_id)

    def get_latest_advisory(self, user_id: str) -> RiskAdvisory | None:
        """Get the most recent advisory for a user."""
        user_advisories = [a for a in self._advisories.values() if a.user_id == user_id]
        if not user_advisories:
            return None
        return max(user_advisories, key=lambda a: a.created_at)

    # ── Knowledge Graph ────────────────────────────────────────────────────

    def add_knowledge_entry(
        self,
        entity_type: str,
        name: str,
        description: str = "",
        properties: dict[str, Any] | None = None,
        relationships: dict[str, list[str]] | None = None,
        embedding: list[float] | None = None,
    ) -> KnowledgeGraphEntry:
        """Add an entry to the knowledge graph."""
        entity_id = f"kg:{uuid.uuid4().hex[:12]}"
        entry = KnowledgeGraphEntry(
            entity_id=entity_id,
            entity_type=entity_type,
            name=name,
            description=description,
            properties=properties or {},
            relationships=relationships or {},
            embedding=embedding,
            updated_at=_now(),
        )
        self._knowledge_graph[entity_id] = entry
        return entry

    def get_knowledge_entry(self, entity_id: str) -> KnowledgeGraphEntry | None:
        """Get a knowledge graph entry by ID."""
        return self._knowledge_graph.get(entity_id)

    def search_knowledge(
        self, query: str, entity_type: str | None = None, limit: int = 10
    ) -> list[KnowledgeGraphEntry]:
        """Search knowledge graph by name or properties."""
        results = []
        query_lower = query.lower()
        for entry in self._knowledge_graph.values():
            if entity_type and entry.entity_type != entity_type:
                continue
            if query_lower in entry.name.lower() or query_lower in entry.description.lower():
                results.append(entry)
            if len(results) >= limit:
                break
        return results

    def update_knowledge_entry(
        self,
        entity_id: str,
        description: str | None = None,
        properties: dict[str, Any] | None = None,
        relationships: dict[str, list[str]] | None = None,
    ) -> KnowledgeGraphEntry | None:
        """Update a knowledge graph entry."""
        entry = self._knowledge_graph.get(entity_id)
        if not entry:
            return None
        if description is not None:
            entry.description = description
        if properties is not None:
            entry.properties.update(properties)
        if relationships is not None:
            entry.relationships.update(relationships)
        entry.updated_at = _now()
        return entry

    # ── Global Config ─────────────────────────────────────────────────────

    def get_user_config(self, user_id: str) -> AIGlobalConfig:
        """Get or create AI config for a user."""
        if user_id not in self._user_configs:
            self._user_configs[user_id] = AIGlobalConfig(config_id=f"aicfg:{uuid.uuid4().hex[:12]}")
        return self._user_configs[user_id]

    def update_user_config(
        self,
        user_id: str,
        default_model: str | None = None,
        temperature: float | None = None,
        enable_knowledge_graph: bool | None = None,
        custom_instructions: str | None = None,
    ) -> AIGlobalConfig:
        """Update AI config for a user."""
        config = self.get_user_config(user_id)
        if default_model is not None:
            config.default_model = default_model
        if temperature is not None:
            config.temperature = temperature
        if enable_knowledge_graph is not None:
            config.enable_knowledge_graph = enable_knowledge_graph
        if custom_instructions is not None:
            config.custom_instructions = custom_instructions
        return config

    # ── AI Chat / LLM Integration (AI-01 ~ AI-07) ───────────────────────────

    def chat(
        self,
        user_id: str,
        query: str,
        context: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Process a user query through AI and return an LLM-generated response (AI-01~AI-07).

        Detects intent and routes to appropriate handler:
        - STRATEGY_DRAFT: Generate trading strategy code
        - STRATEGY_EXPLAIN: Explain a strategy or indicator
        - RESEARCH_ANALYSIS: Provide research analysis
        - RECOMMENDATION: Generate trading recommendation
        - RISK_ADVISORY: Generate risk advisory
        - SCREENER_QUERY: Answer stock screening queries
        - CHART_EXPLANATION: Explain chart patterns
        - PORTFOLIO_REVIEW: Review portfolio and suggest changes
        - GENERAL: Answer general questions
        """
        context = context or {}
        intent = self.detect_intent(query)
        conv_id = context.get("conv_id") or self.create_conversation(user_id)

        # Add user turn
        turn = self.add_turn(conv_id, user_id, query, context)
        if not turn:
            return {"code": "ERROR", "error": "Failed to create conversation turn"}

        response_text = self._generate_llm_response(query, intent, context)
        model = self.get_user_config(user_id).default_model

        # Create AI response turn
        ai_turn = ConversationTurn(
            turn_id=f"turn:{uuid.uuid4().hex[:12]}",
            user_id="ai_assistant",
            intent=intent,
            query=response_text,
            context={"model": model, "intent": intent.value},
            model_used=model,
        )
        self._conversations[conv_id].append(ai_turn)

        return {
            "code": "OK",
            "data": {
                "conv_id": conv_id,
                "turn_id": ai_turn.turn_id,
                "intent": intent.value,
                "response": response_text,
                "model": model,
            },
        }

    def _generate_llm_response(
        self, query: str, intent: AIIntent, context: dict[str, Any]
    ) -> str:
        """Generate LLM response based on intent. Uses LLM client if available, otherwise template."""
        if self._llm_client is not None:
            prompt = self._build_prompt(query, intent, context)
            return self._llm_client.complete(prompt, max_tokens=600)

        # Fallback to template responses
        return self._template_response(query, intent, context)

    def _build_prompt(self, query: str, intent: AIIntent, context: dict[str, Any]) -> str:
        """Build an LLM prompt from query and context."""
        instrument_id = context.get("instrument_id", "UNKNOWN")
        portfolio = context.get("portfolio_summary", "Not provided")
        market_data = context.get("market_data", "Not provided")

        intent_prompts = {
            AIIntent.STRATEGY_DRAFT: (
                f"User wants to create a trading strategy:\n\n{query}\n\n"
                f"Instrument: {instrument_id}\nMarket data context: {market_data}\n\n"
                "Provide a detailed strategy description including: entry conditions, "
                "exit conditions, position sizing, risk management, and timeframe. "
                "Format as a structured response with code examples if applicable."
            ),
            AIIntent.STRATEGY_EXPLAIN: (
                f"User asks for explanation:\n\n{query}\n\n"
                "Provide a clear, educational explanation suitable for a quant trader. "
                "Include practical examples and trading applications."
            ),
            AIIntent.RESEARCH_ANALYSIS: (
                f"User requests research analysis:\n\n{query}\n\n"
                f"Instrument: {instrument_id}\nMarket data: {market_data}\n\n"
                "Provide a comprehensive research analysis with supporting data and reasoning."
            ),
            AIIntent.RECOMMENDATION: (
                f"User asks for trading recommendation:\n\n{query}\n\n"
                f"Instrument: {instrument_id}\nPortfolio: {portfolio}\nMarket data: {market_data}\n\n"
                "Provide a clear BUY/SELL/HOLD recommendation with entry price, "
                "target price, stop loss, time horizon, and key reasoning."
            ),
            AIIntent.RISK_ADVISORY: (
                f"User asks for risk assessment:\n\n{query}\n\n"
                f"Portfolio: {portfolio}\n"
                "Provide a detailed risk analysis including: overall risk level, "
                "key risk factors, concentration risks, and mitigation strategies."
            ),
            AIIntent.SCREENER_QUERY: (
                f"User asks about stock screening:\n\n{query}\n\n"
                f"Market data: {market_data}\n\n"
                "Provide screening criteria and explain which instruments match."
            ),
            AIIntent.CHART_EXPLANATION: (
                f"User asks about chart/technical analysis:\n\n{query}\n\n"
                f"Market data: {market_data}\n\n"
                "Explain the technical pattern, its significance, and potential implications."
            ),
            AIIntent.PORTFOLIO_REVIEW: (
                f"User asks for portfolio review:\n\n{query}\n\n"
                f"Portfolio: {portfolio}\n\n"
                "Provide a comprehensive portfolio review with allocation analysis, "
                "risk assessment, and specific improvement recommendations."
            ),
            AIIntent.GENERAL: (
                f"User asks:\n\n{query}\n\n"
                "Provide a helpful, accurate response based on your knowledge of "
                "quantitative trading, financial markets, and algorithmic trading systems."
            ),
        }
        return intent_prompts.get(intent, intent_prompts[AIIntent.GENERAL])

    def _template_response(
        self, query: str, intent: AIIntent, context: dict[str, Any]
    ) -> str:
        """Template-based response fallback when no LLM is available."""
        template_responses = {
            AIIntent.STRATEGY_DRAFT: (
                "I'd be happy to help you design a trading strategy! "
                "Based on your request, here's a framework:\n\n"
                "**Strategy Components:**\n"
                "1. **Entry Signal**: Define clear technical/fundamental conditions\n"
                "2. **Position Sizing**: Use fixed fractional or Kelly criterion\n"
                "3. **Exit Rules**: Target profit + trailing stop\n"
                "4. **Risk Management**: Max 2% per trade, daily stop\n\n"
                "For a complete strategy, please provide more details about your "
                "preferred instruments, timeframes, and risk tolerance."
            ),
            AIIntent.STRATEGY_EXPLAIN: (
                "Let me explain that concept for you. "
                "This is a quantitative trading concept that involves analyzing "
                "market data to generate actionable signals. "
                "For a detailed explanation, could you specify which aspect "
                "you'd like to understand better?"
            ),
            AIIntent.RESEARCH_ANALYSIS: (
                "Here's my research analysis on your question. "
                "For a comprehensive analysis, I would need access to real-time "
                "market data and your specific research parameters. "
                "Please provide more context about what you're analyzing."
            ),
            AIIntent.RECOMMENDATION: (
                "Based on the information provided, here is my recommendation analysis:\n\n"
                "**Key Factors:**\n"
                "- Risk/reward ratio considerations\n"
                "- Current market conditions\n"
                "- Portfolio alignment\n\n"
                "For a specific BUY/SELL/HOLD recommendation, "
                "please provide the instrument ID and current market context."
            ),
            AIIntent.RISK_ADVISORY: (
                "**Risk Assessment:**\n\n"
                "Your current portfolio exposure shows standard risk metrics. "
                "Key considerations:\n"
                "- Position concentration\n"
                "- Correlation across positions\n"
                "- Volatility regime\n\n"
                "For a detailed risk advisory with specific metrics, "
                "please provide your full portfolio holdings."
            ),
            AIIntent.SCREENER_QUERY: (
                "Based on screening criteria, here are the key factors to consider:\n\n"
                "**Screening Factors:**\n"
                "- Technical indicators (RSI, MACD, moving averages)\n"
                "- Fundamental metrics (P/E, revenue growth, margins)\n"
                "- Market conditions (trend, volatility)\n\n"
                "For specific stock recommendations, please define your criteria."
            ),
            AIIntent.CHART_EXPLANATION: (
                "Looking at the chart pattern you described:\n\n"
                "**Pattern Analysis:**\n"
                "Key observations include price action, volume profile, "
                "and technical indicator readings. "
                "For a detailed chart explanation, please specify the "
                "timeframe and particular pattern you're examining."
            ),
            AIIntent.PORTFOLIO_REVIEW: (
                "**Portfolio Review:**\n\n"
                "A comprehensive review would include:\n"
                "- Asset allocation breakdown\n"
                "- Risk metrics (VaR, drawdown)\n"
                "- Performance attribution\n\n"
                "For a specific review, please share your portfolio details."
            ),
            AIIntent.GENERAL: (
                "Thank you for your question about quant trading. "
                "I can help with strategy design, technical analysis, "
                "risk management, and market research. "
                "Could you please provide more specific details about "
                "what you'd like to know?"
            ),
        }
        return template_responses.get(intent, template_responses[AIIntent.GENERAL])
